### ISSUE TITLE
serialization and deserialization for primitives

### ISSUE THREAD

**Issue by rphmeier** [ethcore/ethkey#5]

**Comment by debris** [comment]
I don't think it should be a part of this library. imo serialization / deserialization should be implemented in the crate using it.

**Comment by rphmeier** [comment]
Could be. They would then have to wrap the primitives in newtypes because of the orphan rules, which makes it pretty annoying to do.

**Comment by debris** [comment]
That's true, but to me it seems to be the most modular approach
